### ISSUE TITLE
The dashboard should be updated to show that all four APZ bugs have been fixed.

### ISSUE THREAD

**Issue by cpeterso** [mozilla/platform-health#10]
* Touch Scrollbar Dragging Bug 1367765 was enabled in Nightly 57 (2017-09-13).
* Keyboard Scrolling Bug 1376525 was enabled in Nightly 57 (2017-09-01).
* Autoscrolling Bug 1385463 was enabled in Nightly 57 (2017-09-02).

**Comment by stuartphilp** [comment]
updated today, thanks!
