### ISSUE TITLE
Label Speedometer graphs with which Chrome channel (Beta or Canary?) we are testing

### ISSUE THREAD

**Issue by cpeterso** [mozilla/platform-health#20]
The question of which Chrome channel (Beta or Canary) we're comparing Firefox Beta and Nightly against has come up a few times. We should label the graphs to avoid the question. Something like:

"Benchmark: Speedometer v2 32-bit Nightly vs Chrome Beta" (unless we are actually testing Canary, IDK)
"Benchmark: Speedometer v2 32-bit Nightly vs Chrome Canary"

**Comment by stuartphilp** [comment]
Updated the labels, let me know if you need any further clarification

**Comment by cpeterso** [comment]
Looks good! I like the new "Talos: Speedometer mozilla-central" graph too because it shows whether a regression in the Speedometer -vs- graph is caused by a Firefox change or not.
