### ISSUE TITLE
Do not restrict CSS imports to only srcDir

### ISSUE THREAD

**Issue by armenzg** [mozilla/platform-health#25]
@wlach @eliperelman I'm trying to add react-metrics-graphics to platform-health, however, I'm getting an issue I can't understand.

When I load http://localhost:3000/quantum from this branch.
I get the following:

> ERROR in ./node_modules/react-metrics-graphics/node_modules/metrics-graphics/dist/metricsgraphics.css
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type.
> | .mg-active-datapoint {
> |     fill: black;
> |     font-size: 0.9rem;
>  @ ./node_modules/react-metrics-graphics/build/MetricsGraphics.js 1:3421-3473
>  @ ./static/plotting.js
>  @ ./static/quantum/index.js
>  @ ./static/routes.js
>  @ ./static/index.js
>  @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true ./index.js

Here's a [link](https://github.com/mozilla/react-metrics-graphics/blob/master/src/components/MetricsGraphics.js#L3) to the code that tries to import the CSS module.

I've tried using the following as indicated in [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/css/README.md#setup):
```javascript
diff --git a/webpack.config.babel.js b/webpack.config.babel.js
index 53d9286..f686bf2 100644
--- a/webpack.config.babel.js
+++ b/webpack.config.babel.js
@@ -83,19 +83,24 @@ export default {
         test: /\.js$/,
         include: srcDir,
         use: 'babel-loader',
       },
       {
         test: /\.css$/,
         include: srcDir,
         use: [
           'style-loader',
-          'css-loader',
+          {
+            loader: 'css-loader',
+            options: {
+              modules: true,
+            },
+          },
           {
             loader: 'postcss-loader',
             options: {
               plugins: () => [
                 postcssImport(),
                 postcssSimpleExtend(),
                 postcssNested(),
                 postcssVariables(),
                 postcssCssnext({
```

**Comment by eliperelman** [comment]
It looks like the CSS file you are importing is not a CSS module, but rather just a plain stylesheet. I typically keep CSS modules enabled only for local project files, or opt-in with the `.module.css` extension. I'd recommend removing the `modules` option and try importing the stylesheet again.

**Comment by armenzg** [comment]
Eli suggested removing the "include: srcDir" for css files.
https://github.com/armenzg/platform-health/commit/e43808e0e7958b4292ccd99c8d8770f2fac70dee

I will get it reviewed and landed.

**Comment by armenzg** [comment]
Fixed: https://github.com/mozilla/platform-health/commit/8e15bb2d49c45801c0dbc6dd94680863ad1d6709
