### ISSUE TITLE
Build issues if trying to include packages using newer syntax

### ISSUE THREAD

**Issue by armenzg** [mozilla/platform-health#30]
CC @eliperelman @digitarald @wlach

I've been trying to separate the frontend and backend because I did not know how to debug a build issue. I see the value of running both from the same URL, thus, here's my attempt at trying to hopefully fix this in an easier way.

I also tried to switch the project to using [Neutrino](https://github.com/armenzg/platform-health/tree/switch_neutrino) but I gave up as well.

I originally reported the *production* build issue in [this comment](https://github.com/mozilla/platform-health/issues/21#issuecomment-353190981) [1]

I believe the issue comes from trying to use es2015-loose with a package (react-metrics-graphics) that has es2016 syntax (I think). See [this issue](https://github.com/webpack/webpack/issues/2972#issuecomment-261705632).

Here's what is mentioned on that comment:

> Uglify cannot parse ES6, it will throw you syntax errors. Either:
> * set TypeScript to target ES5
> * post-process your generated JS with babel
> * or use a different minifier.

This is what the [official documentation](https://babeljs.io/docs/plugins/preset-env#targetsuglify) says:

> When using uglify-js to minify your code, you may run into syntax errors when targeting later browsers since uglify-js does not support any ES2015+ syntax.
> 
> To prevent these errors - set the uglify option to true, which enables all transformation plugins and as a result, your code is fully compiled to ES5. However, the useBuiltIns option will still work as before and only include the polyfills that your target(s) need.
> 
>     Uglify has support for ES2015 syntax via uglify-es. If you are using syntax unsupported by uglify-es, we recommend using babel-minify.

Please let me know if you have any suggestions on what to try.

I'm going to try to switch to babel-minify.

[1]
> ERROR in app.1683db.js from UglifyJs
> Unexpected token: name (l) [../node_modules/react-metrics-graphics/build/MetricsGraphics.js:1,2669][app.1683db.js:106701,2637]
> Child html-webpack-plugin for "index.html":
>      1 asset
>        [0] ../node_modules/html-webpack-plugin/lib/loader.js!./index.html 689 bytes {0} [built]
>         + 3 hidden modules
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wlach** [comment]
As far as I am aware react-metrics-graphics is not using any es2016 idioms. Aside from that, I'm afraid I have no idea.

**Comment by armenzg** [comment]
Thanks @wlach 

For reference, the unexpected token message comes from here [1][2]

I'm at a complete loss. I've read more about babel I would have ever wanted to know.
I've tried many ways to swith to the 'minify' preset (or the 'env' preset) or even disable minify altogether, however, new errors would show up.

I will try one more time to switch to neutrino and if that doesn't work I will separate the project into two parts (as much as I dislike having to start two different projects).

[1]
`Unexpected token: name (l)` 
> class l extends f.a.Component{constructor(a){super(a),this.mgData={}}
> <trimmed the rest since it is a 1 line file>
[2] https://github.com/mozilla/react-metrics-graphics/blob/505574b15856ca19eb0ac5d66243dda1afed2012/src/components/MetricsGraphics.js#L130
