### ISSUE TITLE
upgrade node version

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/platform-health#7]
travis is currently building on node 5, koa requires node 7 (hence the travis failures)

node 7 seems to introduce some other errors possibly around webpack, or browserslist, or caniuse-db (browserslist.queries is undefined)

**Comment by digitarald** [comment]
I run node 8 locally without issues, but it is current version. Might make sense to bump all versions.

**Comment by stuartphilp** [comment]
I pushed a fix for the queries is undefined error to get it working on node 7+, so this should hopefully just be a bump for travis to get it up to date now

**Comment by stuartphilp** [comment]
I upgrade travis to node 8 and it appears there are other areas where queries = undefined, similar patches will have to be made. Here's the travis run

https://travis-ci.org/mozilla/platform-health/builds/277411314

**Comment by stuartphilp** [comment]
fixed up the chrome query and the build is passing again, closing!
