### ISSUE TITLE
investigate adding photon dashboard

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/platform-health#8]
preferably directly pull in, but at least link to the photo dashboard at: http://astithas.com/perm/photon-perf/

this should be in spot #3, just before page load times

**Comment by armenzg** [comment]
I will be looking into this.

**Comment by armenzg** [comment]
@digitarald do you have any suggestions as to how to integrate this? (In case you have already given it some thought).

**Comment by digitarald** [comment]
https://github.com/mozilla/platform-health/blob/6d5b10a3c0a72318aba269530551575f2dd9284e/src/perf.js#L395 has some code that grabs telemetry graphs over versions. It was driving https://health.graphics/quantum/pageload/render (other format: https://health.graphics/quantum/track?metric=GC_MAX_PAUSE_MS&child=content ) , which seems to be broken right now.

**Comment by armenzg** [comment]
I'm hitting this:
```bash
ERROR in ./node_modules/bindings/bindings.js
Module not found: Error: Can't resolve 'fs' in '/Users/armenzg/repos/platform-health/node_modules/bindings'
 @ ./node_modules/bindings/bindings.js 6:9-22
 @ ./node_modules/hiredis/hiredis.js
 @ ./node_modules/redis-parser/lib/hiredis.js
 @ ./node_modules/redis-parser/lib/parser.js
 @ ./node_modules/redis-parser/index.js
 @ ./node_modules/redis/index.js
 @ ./node_modules/then-redis/lib/Client.js
 @ ./node_modules/then-redis/lib/index.js
 @ ./src/fetch/text.js
 @ ./src/fetch/json.js
 @ ./src/release/versions.js
 @ ./static/quantum/photon_perf.js
 @ ./static/quantum/index.js
 @ ./static/routes.js
 @ ./static/index.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true ./index.js
```

`yarn add fs` does not help.

**Comment by digitarald** [comment]
Looks like your node installation is broken, `fs` comes with node.

**Comment by armenzg** [comment]
I removed node_modules and installed again. At the moment I don't hit this issue anymore.

**Comment by armenzg** [comment]
I believe I've figured out how to use telemetry-wrapper to plot this within React:
https://github.com/armenzg/react-telemetry-demo/commit/07f1fb1a0cf1f837364b0a493e142e780be5789b

If @digitarald finds no objections with this approach I will move forward with it.

**Comment by armenzg** [comment]
Finally merged!
https://github.com/mozilla/platform-health/pull/18#event-1331128987

This code makes it easier for other telemetry graphs to be integrated.
